// <auto-generated />
using GYM_AND_FITNESS_MANAGEMENT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GYM_AND_FITNESS_MANAGEMENT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GYM_AND_FITNESS_MANAGEMENT.Models.AddMember", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("Age").HasColumnType("int");
                b.Property<int>("Fee").HasColumnType("int");
                b.Property<string>("MembershipType").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasColumnType("nvarchar(max)");
                b.Property<int>("PhoneNumber").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Members", "dbo");
            });

            modelBuilder.Entity("GYM_AND_FITNESS_MANAGEMENT.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("Age").HasColumnType("int");
                b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Password").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("users");
            });

            modelBuilder.Entity("GYM_AND_FITNESS_MANAGEMENT.Models.FoodItems", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<double>("CaloriesPerUnit").HasColumnType("float");
                b.Property<string>("Name").HasColumnType("nvarchar(max)");
                b.Property<string>("Unit").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("FoodItems");
            });

            modelBuilder.Entity("GYM_AND_FITNESS_MANAGEMENT.Models.Exercises", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("MuscleGroup").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Exercises");
            });

            modelBuilder.Entity("GYM_AND_FITNESS_MANAGEMENT.Models.Workout", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ExerciseName").HasColumnType("nvarchar(max)");
                b.Property<int>("Reps").HasColumnType("int");
                b.Property<int>("Sets").HasColumnType("int");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("workout");
            });

            modelBuilder.Entity("GYM_AND_FITNESS_MANAGEMENT.Models.CaloriesEntry", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<double>("CaloriesPerUnit").HasColumnType("float");
                b.Property<string>("FoodName").HasColumnType("nvarchar(max)");
                b.Property<double>("Quantity").HasColumnType("float");
                b.Property<string>("Unit").HasColumnType("nvarchar(max)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("CaloriesEntries");
            });
#pragma warning restore 612, 618
        }
    }
}
